// I have not looked at these tests at all, they were generated by copilot
// They are just here as a starting point to demonstrate how we can test actions
import { jest, describe, it, expect } from "@jest/globals";
import { onExecutePostLogin } from "./post-login-action.js";

// Mock types for testing
type MockEvent = {
  user: {
    app_metadata: Record<string, unknown>;
  };
  client: {
    name: string;
  };
};

type MockApi = {
  accessToken: {
    setCustomClaim: jest.Mock;
  };
};

const createMockEvent = (
  clientName: string,
  appMetadata: Record<string, unknown>,
): MockEvent => ({
  user: {
    app_metadata: appMetadata,
  },
  client: {
    name: clientName,
  },
});

const createMockApi = (): MockApi => ({
  accessToken: {
    setCustomClaim: jest.fn(),
  },
});

describe("onExecutePostLogin", () => {
  const namespace = "https://login.nine.com.au/entitlements";

  describe("stan client", () => {
    it("should add afr entitlement when user has afr metadata", async () => {
      const event = createMockEvent("stan", { afr: "paid" });
      const api = createMockApi();

      await onExecutePostLogin(event as any, api as any);

      expect(api.accessToken.setCustomClaim).toHaveBeenCalledWith(namespace, {
        afr: "paid",
      });
    });

    it("should add the_age entitlement when user has the_age metadata", async () => {
      const event = createMockEvent("stan", { the_age: "free" });
      const api = createMockApi();

      await onExecutePostLogin(event as any, api as any);

      expect(api.accessToken.setCustomClaim).toHaveBeenCalledWith(namespace, {
        the_age: "free",
      });
    });

    it("should add both afr and the_age entitlements when user has both", async () => {
      const event = createMockEvent("stan", { afr: "paid", the_age: "free" });
      const api = createMockApi();

      await onExecutePostLogin(event as any, api as any);

      expect(api.accessToken.setCustomClaim).toHaveBeenCalledWith(namespace, {
        afr: "paid",
        the_age: "free",
      });
    });

    it("should not include stan entitlement for stan client", async () => {
      const event = createMockEvent("stan", {
        stan: { sport_status: "active" },
        afr: "paid",
      });
      const api = createMockApi();

      await onExecutePostLogin(event as any, api as any);

      expect(api.accessToken.setCustomClaim).toHaveBeenCalledWith(namespace, {
        afr: "paid",
      });
    });
  });

  describe("nine_now client", () => {
    it("should add all entitlements when user has all metadata", async () => {
      const event = createMockEvent("nine_now", {
        afr: "paid",
        the_age: "free",
        stan: { sport_status: "active" },
      });
      const api = createMockApi();

      await onExecutePostLogin(event as any, api as any);

      expect(api.accessToken.setCustomClaim).toHaveBeenCalledWith(namespace, {
        afr: "paid",
        the_age: "free",
        stan: { sport_status: "active" },
      });
    });

    it("should only add available entitlements", async () => {
      const event = createMockEvent("nine_now", { afr: "paid" });
      const api = createMockApi();

      await onExecutePostLogin(event as any, api as any);

      expect(api.accessToken.setCustomClaim).toHaveBeenCalledWith(namespace, {
        afr: "paid",
      });
    });
  });

  describe("afr client", () => {
    it("should add the_age and stan entitlements but not afr", async () => {
      const event = createMockEvent("afr", {
        afr: "paid",
        the_age: "free",
        stan: { entertainment_status: "active" },
      });
      const api = createMockApi();

      await onExecutePostLogin(event as any, api as any);

      expect(api.accessToken.setCustomClaim).toHaveBeenCalledWith(namespace, {
        the_age: "free",
        stan: { entertainment_status: "active" },
      });
    });
  });

  describe("the_age client", () => {
    it("should return empty entitlements as the_age has no client entitlements", async () => {
      const event = createMockEvent("the_age", {
        afr: "paid",
        the_age: "free",
        stan: { sport_status: "active" },
      });
      const api = createMockApi();

      await onExecutePostLogin(event as any, api as any);

      expect(api.accessToken.setCustomClaim).toHaveBeenCalledWith(
        namespace,
        {},
      );
    });
  });

  describe("edge cases", () => {
    it("should return empty entitlements when user has no app_metadata", async () => {
      const event = createMockEvent("stan", {});
      const api = createMockApi();

      await onExecutePostLogin(event as any, api as any);

      expect(api.accessToken.setCustomClaim).toHaveBeenCalledWith(
        namespace,
        {},
      );
    });

    it("should handle undefined app_metadata values gracefully", async () => {
      const event = createMockEvent("stan", { afr: undefined });
      const api = createMockApi();

      await onExecutePostLogin(event as any, api as any);

      expect(api.accessToken.setCustomClaim).toHaveBeenCalledWith(
        namespace,
        {},
      );
    });
  });
});
